#!/usr/bin/env bash
#
# Maintainer:   jeff.irland@gmail.com
# Version:      1.0

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmapfi

if [ -f $sysresources ]; then
    /usr/bin/xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    /usr/bin/xmodmap $sysmodmap
fi

if [ -f $userresources ]; then
    /usr/bin/xrdb -merge $userresources
fi

if [ -f $usermodmap ]; then
    /usr/bin/xmodmap $usermodmap
fi

# play a sound when you start the Xsession
ogg123 /usr/share/sounds/ubuntu/stereo/desktop-login.ogg &

# place a Conky system monitoring display on the desktop background
conky &

# terminal emulation for accessing a UNIX shell in the GNOME environment.
#gnome-terminal --geometry=80x24+600+300 & 
